feat: pin all GStreamer packages to radxa repo
radxa-pkg/vendor-profiles pull request #8
Opened 2024-07-19 06:40 UTC by CodeChenL

* closes https://github.com/radxa-pkg/vendor-profiles/issues/7

2024-07-19 06:41 UTC, RadxaYuntian commented
你先看看是不是全部都要pin吧

2024-07-19 07:30 UTC, CodeChenL commented
@RadxaYuntian request a review

2024-07-19 07:43 UTC, RadxaYuntian requested changes

2024-07-19 07:43 UTC, RadxaYuntian commented on apt/radxa-rk3588
> +
```suggestion

# v4l2src is part of gstreamer1.0-plugins-good
```

2024-07-19 07:44 UTC, RadxaYuntian commented
@Ken-Vamrs 麻烦测试一下只安装gstreamer1.0-plugins-good是不是就可以解决报错问题

2024-07-22 07:49 UTC, RadxaYuntian requested changes
rebase一下，然后等@Ken-Vamrs验证

2024-07-22 08:59 UTC, Ken-Vamrs commented
单独装上这个包之后，可以跑

2024-07-22 09:17 UTC, RadxaYuntian approved these changes

2024-07-22 09:17 UTC, merged